services:

  proxy:
    build:
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
      helloworld_service:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"

  helloworld_service:
    build:
      context: ../shared/python
      target: aiohttp-hello-service

  jaeger:
    build:
      dockerfile: ../shared/jaeger/Dockerfile
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
    - "${PORT_UI:-10001}:16686"
